DROP TABLE IF EXISTS `ast_OrderDetails_TP`;

CREATE TABLE `ast_OrderDetails_TP` ( `orderId` VARCHAR(256) NOT NULL, `orderItemId` VARCHAR(256) NOT NULL, `itemId` VARCHAR(256) NOT NULL, `itemPrice` DOUBLE(10,2) NULL DEFAULT NULL, `itemQuantity` INT(10) NOT NULL, `subTotal` DOUBLE(10,2) NOT NULL, `createdBy` VARCHAR(64) NULL DEFAULT '-1', `createdDate` TIMESTAMP NULL DEFAULT '2000-01-01 10:10:10', `updatedBy` VARCHAR(64) NULL DEFAULT '-1', `updatedDate` TIMESTAMP NULL DEFAULT '2000-01-01 10:10:10', `versionId` INT(10) NULL DEFAULT '-1', `activeStatus` INT(1) NULL DEFAULT '1', `txnAccessCode` INT(10) NULL DEFAULT NULL, PRIMARY KEY (`orderItemId`));

