Ext.define('Startone.startone.shared.com.model.shoppingcontext.onlineshopping.CategoryModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "primaryKey",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "categoryId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "productid",
          "reference": "Product",
          "defaultValue": ""
     }, {
          "name": "categoryName",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "versionId",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "entityAudit",
          "reference": "EntityAudit"
     }, {
          "name": "primaryDisplay",
          "type": "string",
          "defaultValue": ""
     }]
});